// Maps the dataset's IAU 3-letter constellation codes to full names. Codes were pulled
// from the API's own facet listing (not guessed) to confirm exactly which are in use;
// a couple of stray lowercase variants ("Cma", "Uma") appear in the source data as
// data-entry quirks, handled by the case-insensitive fallback in getConstellationName.
const CONSTELLATION_NAMES = {
    And: 'Andromeda',
    Ant: 'Antlia',
    Aps: 'Apus',
    Aqr: 'Aquarius',
    Aql: 'Aquila',
    Ara: 'Ara',
    Ari: 'Aries',
    Aur: 'Auriga',
    Boo: 'Boötes',
    Cae: 'Caelum',
    Cam: 'Camelopardalis',
    Cnc: 'Cancer',
    CVn: 'Canes Venatici',
    CMa: 'Canis Major',
    CMi: 'Canis Minor',
    Cap: 'Capricornus',
    Car: 'Carina',
    Cas: 'Cassiopeia',
    Cen: 'Centaurus',
    Cep: 'Cepheus',
    Cet: 'Cetus',
    Cha: 'Chamaeleon',
    Cir: 'Circinus',
    Col: 'Columba',
    Com: 'Coma Berenices',
    CrA: 'Corona Australis',
    CrB: 'Corona Borealis',
    Crv: 'Corvus',
    Crt: 'Crater',
    Cru: 'Crux',
    Cyg: 'Cygnus',
    Del: 'Delphinus',
    Dor: 'Dorado',
    Dra: 'Draco',
    Equ: 'Equuleus',
    Eri: 'Eridanus',
    For: 'Fornax',
    Gem: 'Gemini',
    Gru: 'Grus',
    Her: 'Hercules',
    Hor: 'Horologium',
    Hya: 'Hydra',
    Hyi: 'Hydrus',
    Ind: 'Indus',
    Lac: 'Lacerta',
    Leo: 'Leo',
    LMi: 'Leo Minor',
    Lep: 'Lepus',
    Lib: 'Libra',
    Lup: 'Lupus',
    Lyn: 'Lynx',
    Lyr: 'Lyra',
    Men: 'Mensa',
    Mic: 'Microscopium',
    Mon: 'Monoceros',
    Mus: 'Musca',
    Nor: 'Norma',
    Oct: 'Octans',
    Oph: 'Ophiuchus',
    Ori: 'Orion',
    Pav: 'Pavo',
    Peg: 'Pegasus',
    Per: 'Perseus',
    Phe: 'Phoenix',
    Pic: 'Pictor',
    Psc: 'Pisces',
    PsA: 'Piscis Austrinus',
    Pup: 'Puppis',
    Pyx: 'Pyxis',
    Ret: 'Reticulum',
    Sge: 'Sagitta',
    Sgr: 'Sagittarius',
    Sco: 'Scorpius',
    Scl: 'Sculptor',
    Sct: 'Scutum',
    Ser: 'Serpens',
    Sex: 'Sextans',
    Tau: 'Taurus',
    Tel: 'Telescopium',
    Tri: 'Triangulum',
    TrA: 'Triangulum Australe',
    Tuc: 'Tucana',
    UMa: 'Ursa Major',
    UMi: 'Ursa Minor',
    Vel: 'Vela',
    Vir: 'Virgo',
    Vol: 'Volans',
    Vul: 'Vulpecula',
};

const LOWERCASE_INDEX = Object.fromEntries(
    Object.entries(CONSTELLATION_NAMES).map(([code, name]) => [code.toLowerCase(), name])
);

export function getConstellationName(code) {
    if (!code || code === '-') return null;
    return CONSTELLATION_NAMES[code] ?? LOWERCASE_INDEX[code.toLowerCase()] ?? code;
}
